import { z } from 'zod';

export const eventResponse = z.object({
    id: z.string(),
    slug: z.string(),
    title: z.string(),
    type: z.string(),
    is_published: z.boolean(),
    is_private: z.boolean(),
    service_fee: z.number(),
    absorve_fee: z.boolean(),
    description: z.string().nullable(),
    category_id: z.string().nullable(),
    banner_asset_id: z.string().nullable(),
    thumbnail_asset_id: z.string().nullable(),
    opengraph_asset_id: z.string().nullable(),
    age_rating: z.string(),
    start_date: z.date().transform((d) => d.toISOString()),
    end_date: z.date().transform((d) => d.toISOString()),
    sales_starts_at: z.date().transform((d) => d.toISOString()),
    sales_ends_at: z.date().transform((d) => d.toISOString()),
    address_name: z.string().nullable(),
    address_zip_code: z.string().nullable(),
    address_country: z.string().nullable(),
    address_region: z.string().nullable(),
    address_city: z.string().nullable(),
    address_line: z.string().nullable(),
    gmaps_url: z.string().nullable(),
    facebook_url: z.string().nullable(),
    instagram_url: z.string().nullable(),
    twitter_url: z.string().nullable(),
    tiktok_url: z.string().nullable(),
    site_url: z.string().nullable(),
});
